import RawHtml from '@/components/RawHtml';

const html = `

<div class="svc-hero"><div class="svc-hero-inner"><div><button class="back-btn" data-route="/">← Volver</button><div class="svc-hero-badge"><svg fill="none" height="12" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24" width="12"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"></polyline></svg><span>Bonsight Growth</span></div><h1>Growth Digital</h1><button class="btn-primary" data-route="/">Conversemos</button></div><p class="svc-hero-desc">Impulsamos el crecimiento digital con analítica y performance. Conectamos datos, audiencias y canales para optimizar la inversión y acelerar tráfico, ventas y posicionamiento.</p></div></div>
<div class="svc-body"><div class="svc-grid"><div><div class="eyebrow">Qué incluye</div><h2 style="font-family:var(--serif);font-size:1.5rem;font-weight:400;margin-bottom:1.5rem">Servicios incluidos</h2><div class="svc-items-list"><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><path d="M22 12h-4l-3 9L9 3l-3 9H2"></path></svg></div><div><h4>Estrategia de adquisición</h4><p>Canales pagos y orgánicos optimizados para atraer usuarios de alta calidad al menor costo.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><line x1="18" x2="18" y1="20" y2="10"></line><line x1="12" x2="12" y1="20" y2="4"></line><line x1="6" x2="6" y1="20" y2="14"></line></svg></div><div><h4>Analítica de marketing</h4><p>Sistemas de medición end-to-end para entender qué canales y mensajes generan mayor impacto.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><line x1="12" x2="12" y1="1" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg></div><div><h4>Optimización de inversión</h4><p>Redistribución continua del presupuesto basada en datos de performance real.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><circle cx="11" cy="11" r="8"></circle><path d="M21 21l-4.35-4.35"></path></svg></div><div><h4>SEO y posicionamiento orgánico</h4><p>Estrategias de contenido y técnicas para mejorar visibilidad orgánica de forma sostenida.</p></div></div></div></div><div class="outcomes-panel"><h3>Lo que lograrás</h3><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Más tráfico calificado</h4><p>Usuarios con mayor intención de compra y mejor fit con tu producto.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Mejor ROAS</h4><p>Mayor retorno sobre inversión publicitaria con presupuesto optimizado.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Crecimiento sostenible</h4><p>Estrategias que funcionan a corto y largo plazo sin depender de un solo canal.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Visibilidad de marca</h4><p>Mayor presencia digital en los canales donde está tu audiencia clave.</p></div></div></div></div></div>
<div class="svc-process"><div class="svc-process-inner" style="max-width:1200px;margin:0 auto"><div class="eyebrow" style="color:var(--accent-mid)"><span style="display:inline-block;width:16px;height:1px;background:var(--accent-mid)"></span> Proceso</div><h2 style="font-family:var(--serif);font-size:1.8rem;font-weight:400;color:white;margin-bottom:2rem">Cómo trabajamos</h2><div class="process-steps"><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">01</div></div><h4 style="color:white">Auditoría</h4><p style="color:rgba(255,255,255,0.45)">Analizamos canales, audiencias y performance actual de marketing.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">02</div></div><h4 style="color:white">Estrategia</h4><p style="color:rgba(255,255,255,0.45)">Definimos mix de canales, objetivos y KPIs de crecimiento priorizados.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">03</div></div><h4 style="color:white">Ejecución</h4><p style="color:rgba(255,255,255,0.45)">Implementamos campañas con foco en datos y mejora continua.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">04</div></div><h4 style="color:white">Optimización</h4><p style="color:rgba(255,255,255,0.45)">Ajustes en tiempo real basados en performance para maximizar resultados.</p></div></div></div></div>
<div class="cta-band"><h2>¿Quieres acelerar tu crecimiento?</h2><p>Hablemos sobre cómo escalar tu adquisición y mejorar tu inversión en marketing.</p><button class="btn-white" data-route="/">Agendar conversación →</button></div>
<footer><div class="footer-logo">BON<span>sight</span> LLC</div><p>© 2025 Bonsight LLC</p></footer>

`;

export default function GrowthPage() {
  return <RawHtml html={html} />;
}
