import RawHtml from '@/components/RawHtml';

const html = `

<div class="svc-hero"><div class="svc-hero-inner"><div><button class="back-btn" data-route="/">← Volver</button><div class="svc-hero-badge"><svg fill="none" height="12" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24" width="12"><circle cx="11" cy="11" r="8"></circle><path d="M21 21l-4.35-4.35"></path></svg><span>Bonsight Growth</span></div><h1>CRO — Optimización de Conversión</h1><button class="btn-primary" data-route="/">Conversemos</button></div><p class="svc-hero-desc">Optimizamos la conversión y la experiencia del usuario. Aplicamos analítica, experimentación y diseño para incrementar ventas y elevar la satisfacción en cada punto de contacto.</p></div></div>
<div class="svc-body"><div class="svc-grid"><div><div class="eyebrow">Qué incluye</div><h2 style="font-family:var(--serif);font-size:1.5rem;font-weight:400;margin-bottom:1.5rem">Servicios incluidos</h2><div class="svc-items-list"><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path></svg></div><div><h4>Análisis del funnel de conversión</h4><p>Identificamos dónde pierdes usuarios y el impacto económico de cada punto de fricción.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"></polyline></svg></div><div><h4>Experimentación y A/B testing</h4><p>Experimentos para validar hipótesis de mejora con rigor estadístico y metodología sólida.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></div><div><h4>UX Research y usabilidad</h4><p>Investigamos el comportamiento de tus usuarios para encontrar oportunidades de mejora.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg></div><div><h4>Personalización</h4><p>Experiencias personalizadas por segmento, canal y etapa del funnel para maximizar relevancia.</p></div></div></div></div><div class="outcomes-panel"><h3>Lo que lograrás</h3><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Mayor tasa de conversión</h4><p>Más ventas con el mismo tráfico que ya tienes hoy en tu sitio.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Menor CAC</h4><p>Reducción del costo de adquisición al mejorar la eficiencia del funnel.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Mejor UX</h4><p>Experiencia más fluida que incrementa satisfacción y retención de usuarios.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Cultura de experimentación</h4><p>Tu equipo aprende a decidir con datos validados, no con opiniones.</p></div></div></div></div></div>
<div class="svc-process"><div class="svc-process-inner" style="max-width:1200px;margin:0 auto"><div class="eyebrow" style="color:var(--accent-mid)"><span style="display:inline-block;width:16px;height:1px;background:var(--accent-mid)"></span> Proceso</div><h2 style="font-family:var(--serif);font-size:1.8rem;font-weight:400;color:white;margin-bottom:2rem">Cómo trabajamos</h2><div class="process-steps"><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">01</div></div><h4 style="color:white">Diagnóstico</h4><p style="color:rgba(255,255,255,0.45)">Mapeamos el funnel e identificamos cuellos de botella con datos cualitativos y cuantitativos.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">02</div></div><h4 style="color:white">Hipótesis</h4><p style="color:rgba(255,255,255,0.45)">Generamos hipótesis priorizadas por impacto potencial y nivel de confianza.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">03</div></div><h4 style="color:white">Experimentos</h4><p style="color:rgba(255,255,255,0.45)">Diseñamos y ejecutamos tests con metodología rigurosa para validar cada hipótesis.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">04</div></div><h4 style="color:white">Aprendizaje</h4><p style="color:rgba(255,255,255,0.45)">Consolidamos aprendizajes y escalamos lo que funciona.</p></div></div></div></div>
<div class="cta-band"><h2>¿Quieres mejorar tu conversión?</h2><p>Hablemos sobre cómo convertir más con los usuarios que ya tienes.</p><button class="btn-white" data-route="/">Agendar conversación →</button></div>
<footer><div class="footer-logo">BON<span>sight</span> LLC</div><p>© 2025 Bonsight LLC</p></footer>

`;

export default function CroPage() {
  return <RawHtml html={html} />;
}
