import RawHtml from '@/components/RawHtml';

const html = `

<div class="svc-hero"><div class="svc-hero-inner"><div><button class="back-btn" data-route="/">← Volver</button><div class="svc-hero-badge"><svg fill="none" height="12" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24" width="12"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg><span>Bonsight Boost</span></div><h1>Mentoring de Equipos</h1><button class="btn-primary">Conversemos</button></div><p class="svc-hero-desc">Impulsamos la autonomía y la calidad de los equipos. Acompañamos con feedback continuo y guía estratégica para fortalecer capacidades y construir equipos de alto rendimiento.</p></div></div>
<div class="svc-body"><div class="svc-grid"><div><div class="eyebrow">Qué incluye</div><h2 style="font-family:var(--serif);font-size:1.5rem;font-weight:400;margin-bottom:1.5rem">Servicios incluidos</h2><div class="svc-items-list"><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle></svg></div><div><h4>Diagnóstico de madurez del equipo</h4><p>Evaluamos habilidades, dinámicas y brechas para diseñar un plan de desarrollo personalizado.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg></div><div><h4>Sesiones de mentoring individual y grupal</h4><p>Sesiones estructuradas de feedback, orientación y desarrollo de competencias clave.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><rect height="14" rx="2" width="20" x="2" y="3"></rect><line x1="8" x2="16" y1="21" y2="21"></line></svg></div><div><h4>Desarrollo de capacidades técnicas</h4><p>Formación en analítica digital, herramientas de datos y buenas prácticas técnicas.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><line x1="12" x2="12" y1="20" y2="10"></line><line x1="18" x2="18" y1="20" y2="4"></line><line x1="6" x2="6" y1="20" y2="16"></line></svg></div><div><h4>Plan de carrera y crecimiento</h4><p>Trayectorias claras para cada miembro alineadas con los objetivos de la organización.</p></div></div></div></div><div class="outcomes-panel"><h3>Lo que lograrás</h3><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Mayor autonomía</h4><p>Equipos que toman mejores decisiones de forma independiente y consistente.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Mejor desempeño</h4><p>Elevación medible en calidad del trabajo y velocidad de ejecución.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Retención de talento</h4><p>Personas que se desarrollan y eligen quedarse en la organización.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Cultura de aprendizaje</h4><p>Equipos que aprenden continuamente y se adaptan mejor al cambio.</p></div></div></div></div></div>
<div class="svc-process"><div class="svc-process-inner" style="max-width:1200px;margin:0 auto"><div class="eyebrow" style="color:var(--accent-mid)"><span style="display:inline-block;width:16px;height:1px;background:var(--accent-mid)"></span> Proceso</div><h2 style="font-family:var(--serif);font-size:1.8rem;font-weight:400;color:white;margin-bottom:2rem">Cómo trabajamos</h2><div class="process-steps"><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">01</div></div><h4 style="color:white">Evaluación</h4><p style="color:rgba(255,255,255,0.45)">Diagnóstico de habilidades, dinámicas y objetivos del equipo.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">02</div></div><h4 style="color:white">Plan</h4><p style="color:rgba(255,255,255,0.45)">Programa de mentoring adaptado a cada contexto y necesidad.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">03</div></div><h4 style="color:white">Acompañamiento</h4><p style="color:rgba(255,255,255,0.45)">Sesiones regulares con feedback continuo y seguimiento de avance.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">04</div></div><h4 style="color:white">Medición</h4><p style="color:rgba(255,255,255,0.45)">Evaluamos el progreso y ajustamos el programa según resultados.</p></div></div></div></div>
<div class="cta-band"><h2>¿Quieres potenciar a tu equipo?</h2><p>Conversemos sobre cómo desarrollar las capacidades que tu equipo necesita.</p><button class="btn-white">Agendar conversación →</button></div>
<footer><div class="footer-logo">BON<span>sight</span> LLC</div><p>© 2025 Bonsight LLC</p></footer>

`;

export default function MentoringPage() {
  return <RawHtml html={html} />;
}
