import RawHtml from '@/components/RawHtml';

const html = `

<div class="svc-hero"><div class="svc-hero-inner"><div><button class="back-btn" data-route="/">← Volver</button><div class="svc-hero-badge"><svg fill="none" height="12" stroke="currentColor" stroke-width="2" viewbox="0 0 24 24" width="12"><polyline points="17 1 21 5 17 9"></polyline><path d="M3 11V9a4 4 0 0 1 4-4h14"></path></svg><span>Bonsight Boost</span></div><h1>Mejora de Procesos</h1><button class="btn-primary" data-route="/">Conversemos</button></div><p class="svc-hero-desc">Hacemos que los equipos trabajen mejor. Optimizamos metodologías y flujos de trabajo para lograr mayor agilidad, foco y eficiencia operativa sostenida en el tiempo.</p></div></div>
<div class="svc-body"><div class="svc-grid"><div><div class="eyebrow">Qué incluye</div><h2 style="font-family:var(--serif);font-size:1.5rem;font-weight:400;margin-bottom:1.5rem">Servicios incluidos</h2><div class="svc-items-list"><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><circle cx="11" cy="11" r="8"></circle><path d="M21 21l-4.35-4.35"></path></svg></div><div><h4>Mapeo de procesos actuales</h4><p>Documentamos y analizamos flujos de trabajo para identificar ineficiencias y cuellos de botella.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><polyline points="17 1 21 5 17 9"></polyline><path d="M3 11V9a4 4 0 0 1 4-4h14M7 23l-4-4 4-4"></path><path d="M21 13v2a4 4 0 0 1-4 4H3"></path></svg></div><div><h4>Rediseño de metodologías</h4><p>Frameworks ágiles y mejores prácticas adaptadas al contexto y madurez de cada equipo.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><rect height="8" rx="2" width="20" x="2" y="2"></rect><rect height="8" rx="2" width="20" x="2" y="14"></rect><line x1="6" x2="6.01" y1="6" y2="6"></line><line x1="6" x2="6.01" y1="18" y2="18"></line></svg></div><div><h4>Automatización y herramientas</h4><p>Oportunidades de automatización y selección de herramientas adecuadas para cada proceso.</p></div></div><div class="svc-item"><div class="svc-item-icon"><svg viewbox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg></div><div><h4>Gestión del cambio</h4><p>Acompañamos la adopción de nuevos procesos para una incorporación efectiva y duradera.</p></div></div></div></div><div class="outcomes-panel"><h3>Lo que lograrás</h3><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Mayor eficiencia</h4><p>Menos tiempo en tareas que no agregan valor, más foco en lo importante.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Entregas más rápidas</h4><p>Ciclos ágiles y predecibles con menor tiempo de espera entre etapas.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Menor fricción interna</h4><p>Procesos claros que reducen confusión, reprocesos y conflictos de equipo.</p></div></div><div class="outcome-item"><div class="outcome-dot"><svg viewbox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div><h4>Escalabilidad operativa</h4><p>Procesos que funcionan igual cuando el equipo o el negocio crece.</p></div></div></div></div></div>
<div class="svc-process"><div class="svc-process-inner" style="max-width:1200px;margin:0 auto"><div class="eyebrow" style="color:var(--accent-mid)"><span style="display:inline-block;width:16px;height:1px;background:var(--accent-mid)"></span> Proceso</div><h2 style="font-family:var(--serif);font-size:1.8rem;font-weight:400;color:white;margin-bottom:2rem">Cómo trabajamos</h2><div class="process-steps"><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">01</div></div><h4 style="color:white">Diagnóstico</h4><p style="color:rgba(255,255,255,0.45)">Observamos y documentamos el estado actual de los procesos clave.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">02</div></div><h4 style="color:white">Diseño</h4><p style="color:rgba(255,255,255,0.45)">Proponemos el nuevo flujo optimizado y consensuado con el equipo.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">03</div></div><h4 style="color:white">Implementación</h4><p style="color:rgba(255,255,255,0.45)">Acompañamos la transición y formamos al equipo en las nuevas metodologías.</p></div><div class="proc-step"><div class="proc-num-wrap" style="background:rgba(255,255,255,0.08);border-color:rgba(255,255,255,0.15)"><div class="proc-num" style="color:rgba(255,255,255,0.4)">04</div></div><h4 style="color:white">Seguimiento</h4><p style="color:rgba(255,255,255,0.45)">Medimos el impacto y refinamos los procesos de forma continua.</p></div></div></div></div>
<div class="cta-band"><h2>¿Quieres que tu equipo trabaje mejor?</h2><p>Conversemos sobre cómo optimizar los procesos que frenan el crecimiento.</p><button class="btn-white" data-route="/">Agendar conversación →</button></div>
<footer><div class="footer-logo">BON<span>sight</span> LLC</div><p>© 2025 Bonsight LLC</p></footer>

`;

export default function ProcesosPage() {
  return <RawHtml html={html} />;
}
